import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: NextRequest) {
  try {
    const { to, subject, type, data } = await request.json();
    
    if (!to || !subject || !type || !data) {
      return NextResponse.json(
        { error: 'Missing required fields: to, subject, type, data' },
        { status: 400 }
      );
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(to)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      );
    }

    // Check if email service is configured
    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASSWORD) {
      return NextResponse.json(
        { error: 'Email service not configured. Please set EMAIL_USER and EMAIL_PASSWORD in .env.local' },
        { status: 500 }
      );
    }

    // Create transporter
    const transporter = nodemailer.createTransport({
      service: process.env.EMAIL_SERVICE || 'gmail',
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASSWORD,
      },
    });

    // Generate email content based on type
    const emailContent = generateEmailContent(type, data);

    // Send email
    await transporter.sendMail({
      from: process.env.EMAIL_FROM || `"CyberSmater" <${process.env.EMAIL_USER}>`,
      to: to,
      subject: subject,
      html: emailContent,
    });

    return NextResponse.json({ message: 'Email sent successfully' });
  } catch (error) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { error: 'Failed to send email' },
      { status: 500 }
    );
  }
}

function generateEmailContent(type: string, data: any): string {
  const baseStyle = `
    <style>
      body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
      .container { max-width: 600px; margin: 0 auto; padding: 20px; }
      .header { background: linear-gradient(135deg, #1e3a8a, #7c2d12); color: white; padding: 20px; text-align: center; }
      .content { padding: 20px; background: #f9fafb; }
      .footer { text-align: center; padding: 20px; color: #6b7280; font-size: 12px; }
      .alert { background: #fef3c7; border-left: 4px solid #f59e0b; padding: 15px; margin: 15px 0; }
      .success { background: #d1fae5; border-left: 4px solid #10b981; padding: 15px; margin: 15px 0; }
      .error { background: #fee2e2; border-left: 4px solid #ef4444; padding: 15px; margin: 15px 0; }
    </style>
  `;

  switch (type) {
    case 'notification':
      return `
        ${baseStyle}
          <div class="container">
            <div class="header">
              <h1>CyberSmater Notification</h1>
            </div>
          <div class="content">
            <h2>${data.title}</h2>
              <p>${data.message}</p>
            </div>
            <div class="footer">
            <p>This email was sent from CyberSmater Business Management System</p>
          </div>
        </div>
      `;

    case 'alert':
      return `
        ${baseStyle}
          <div class="container">
            <div class="header">
              <h1>CyberSmater Alert</h1>
            </div>
          <div class="content">
            <div class="alert">
              <h2>${data.title}</h2>
              <p>${data.message}</p>
            </div>
          </div>
          <div class="footer">
            <p>This alert was sent from CyberSmater Business Management System</p>
          </div>
        </div>
      `;

    case 'summary':
      return `
        ${baseStyle}
          <div class="container">
            <div class="header">
              <h1>CyberSmater Daily Summary</h1>
            </div>
          <div class="content">
            <h2>${data.title}</h2>
            <p>${data.message}</p>
            ${data.details ? `<div class="details">${data.details}</div>` : ''}
            </div>
            <div class="footer">
            <p>This summary was generated by CyberSmater Business Management System</p>
          </div>
        </div>
      `;

    default:
      return `
        ${baseStyle}
          <div class="container">
            <div class="header">
              <h1>CyberSmater Message</h1>
            </div>
          <div class="content">
            <h2>${data.title || 'Message'}</h2>
            <p>${data.message}</p>
          </div>
            <div class="footer">
            <p>This message was sent from CyberSmater Business Management System</p>
          </div>
        </div>
      `;
  }
} 